#include "generated/actions.h"
#include "generated/screens.h"
#include "dro_core.h"
#include "dro_nvs.h"
#include "esp_log.h"
#include <string.h>
#include <stdlib.h> // For atoi, atof

static const char *TAG = "EEZ_UI_EVENTS";

// --- Action Implementations ---

void action_change_to_setting_page(lv_event_t * e) {
    // Generated by EEZ Studio, typically handled by flow
    lv_scr_load(objects.setings_page);
}

void action_settings_mm_switch_pressed(lv_event_t * e) {
    // Use DRO core to toggle units
    const dro_system_state_t* state = dro_get_state();
    if (state->current_unit == DRO_UNIT_MM) {
        // Only toggle if we are staying in sync (optional check)
    }
    dro_toggle_units();
}

// --- Manually Mapped Events ---

static void event_axis_zero(lv_event_t * e) {
    uint8_t axis = (uint8_t)(uintptr_t)lv_event_get_user_data(e);
    dro_axis_zero(axis);
    ESP_LOGI(TAG, "Zeroed Axis %d", axis);
}

static void event_toggle_units(lv_event_t * e) {
    dro_toggle_units();
}

static void event_toggle_mode(lv_event_t * e) {
    dro_toggle_mode();
}

// --- Numpad / Set Value Logic ---

typedef enum {
    INPUT_MODE_NONE = 0,
    INPUT_MODE_AXIS_VALUE,
    INPUT_MODE_TOOL_INDEX,
    INPUT_MODE_SPACE_INDEX
} input_mode_t;

static input_mode_t current_input_mode = INPUT_MODE_NONE;
static int8_t current_target_index = -1; // Axis index or other index

static void prepare_input_ui(const char* placeholder) {
    if (objects.info_text_area) {
        lv_textarea_set_text(objects.info_text_area, "");
        lv_textarea_set_placeholder_text(objects.info_text_area, placeholder);
        
        // Force focus to the text area so the cursor appears and input works
        lv_obj_add_state(objects.info_text_area, LV_STATE_FOCUSED);
        
        if (objects.numpad) {
            lv_keyboard_set_textarea(objects.numpad, objects.info_text_area);
            // Ensure the keyboard is visible and enabled
            lv_obj_clear_flag(objects.numpad, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

static void event_set_value_request(lv_event_t * e) {
    uint8_t axis = (uint8_t)(uintptr_t)lv_event_get_user_data(e);
    current_target_index = axis;
    current_input_mode = INPUT_MODE_AXIS_VALUE;
    
    char buf[32];
    snprintf(buf, sizeof(buf), "Set Axis %d Value...", axis);
    prepare_input_ui(buf);
    
    ESP_LOGI(TAG, "Input Context: Axis %d Value", axis);
}

static void event_set_tool_request(lv_event_t * e) {
    current_target_index = 0; // Not used for global tool, but reset anyway
    current_input_mode = INPUT_MODE_TOOL_INDEX;
    prepare_input_ui("Enter Tool Number...");
    ESP_LOGI(TAG, "Input Context: Tool Number");
}

static void event_set_space_request(lv_event_t * e) {
    current_target_index = 0;
    current_input_mode = INPUT_MODE_SPACE_INDEX;
    prepare_input_ui("Enter Space Number...");
    ESP_LOGI(TAG, "Input Context: Space Number");
}

static void event_half_request(lv_event_t * e) {
    // Logic: If we are in AXIS_VALUE mode, we halve that axis
    
    if (current_input_mode == INPUT_MODE_AXIS_VALUE && current_target_index >= 0) {
        dro_axis_half(current_target_index);
        ESP_LOGI(TAG, "Half function applied to Axis %d", current_target_index);
        
        // Reset mode after action
        current_input_mode = INPUT_MODE_NONE;
        current_target_index = -1;
        if (objects.info_text_area) lv_textarea_set_text(objects.info_text_area, "Halved");
        if (objects.numpad) lv_keyboard_set_textarea(objects.numpad, NULL);
    } else {
        ESP_LOGW(TAG, "Half button ignored: No axis selected");
        if (objects.info_text_area) lv_textarea_set_text(objects.info_text_area, "Select Axis First");
    }
}

static void event_numpad_ready(lv_event_t * e) {
    if (!objects.info_text_area) return;
    const char* txt = lv_textarea_get_text(objects.info_text_area);
    
    switch (current_input_mode) {
        case INPUT_MODE_AXIS_VALUE:
            if (current_target_index >= 0) {
                float val = atof(txt);
                dro_axis_set_value(current_target_index, val);
                ESP_LOGI(TAG, "Set Axis %d to %f", current_target_index, val);
            }
            break;
            
        case INPUT_MODE_TOOL_INDEX:
            {
                int32_t tool_idx = atoi(txt);
                dro_tool_apply(tool_idx);
                ESP_LOGI(TAG, "Applied Tool %ld", (long)tool_idx);
            }
            break;

        case INPUT_MODE_SPACE_INDEX:
            {
                int32_t space_idx = atoi(txt);
                dro_workspace_apply(space_idx);
                ESP_LOGI(TAG, "Applied Space %ld", (long)space_idx);
            }
            break;
            
        default:
            break;
    }
    
    // Cleanup
    current_input_mode = INPUT_MODE_NONE;
    current_target_index = -1;
    lv_textarea_set_text(objects.info_text_area, "Ready");
    if (objects.numpad) lv_keyboard_set_textarea(objects.numpad, NULL);
}

static void event_numpad_cancel(lv_event_t * e) {
    current_input_mode = INPUT_MODE_NONE;
    current_target_index = -1;
    if (objects.info_text_area) {
        lv_textarea_set_text(objects.info_text_area, "Cancelled");
    }
    if (objects.numpad) lv_keyboard_set_textarea(objects.numpad, NULL);
}

// Map the buttons from objects structure to our handlers
void dro_ui_events_init(void) {
    // Disable clickability on axis display text areas to prevent focus theft
    lv_obj_t *axis_textareas[] = {
        objects.axis1_textarea,
        objects.axis2_textarea,
        objects.axis3_textarea,
        objects.axis4_textarea,
        objects.axis5_textarea
    };
    
    for (int i = 0; i < 5; i++) {
        if (axis_textareas[i]) {
            lv_obj_clear_flag(axis_textareas[i], LV_OBJ_FLAG_CLICKABLE);
            // Also ensure they don't get focus via navigation
            lv_obj_clear_flag(axis_textareas[i], LV_OBJ_FLAG_SCROLLABLE); 
            lv_obj_add_state(axis_textareas[i], LV_STATE_DISABLED); // Optional: if visual style allows
            // Better: just remove from group if groups are used, but clearing CLICKABLE usually works for touch
        }
    }

    // Axis Zero Buttons
    if (objects.set_zero_axis1_button) lv_obj_add_event_cb(objects.set_zero_axis1_button, event_axis_zero, LV_EVENT_CLICKED, (void*)DRO_AXIS_X);
    if (objects.set_zero_axis2_button) lv_obj_add_event_cb(objects.set_zero_axis2_button, event_axis_zero, LV_EVENT_CLICKED, (void*)DRO_AXIS_Y);
    if (objects.set_zero_axis_3_button) lv_obj_add_event_cb(objects.set_zero_axis_3_button, event_axis_zero, LV_EVENT_CLICKED, (void*)DRO_AXIS_Z); // Note: "axis_3" naming quirk
    if (objects.set_zero_axis4_button) lv_obj_add_event_cb(objects.set_zero_axis4_button, event_axis_zero, LV_EVENT_CLICKED, (void*)DRO_AXIS_W);
    if (objects.set_zero_axis5_button) lv_obj_add_event_cb(objects.set_zero_axis5_button, event_axis_zero, LV_EVENT_CLICKED, (void*)DRO_AXIS_C);

    // Global Toggles
    if (objects.toggle_inch_mm_button) lv_obj_add_event_cb(objects.toggle_inch_mm_button, event_toggle_units, LV_EVENT_CLICKED, NULL);
    if (objects.toggle_abs_incr_button) lv_obj_add_event_cb(objects.toggle_abs_incr_button, event_toggle_mode, LV_EVENT_CLICKED, NULL);
    
    // Set Value via Numpad
    if (objects.set_value_axis1_button) lv_obj_add_event_cb(objects.set_value_axis1_button, event_set_value_request, LV_EVENT_CLICKED, (void*)DRO_AXIS_X);
    if (objects.set_value_axis2_button) lv_obj_add_event_cb(objects.set_value_axis2_button, event_set_value_request, LV_EVENT_CLICKED, (void*)DRO_AXIS_Y);
    if (objects.set_value_axis3_button) lv_obj_add_event_cb(objects.set_value_axis3_button, event_set_value_request, LV_EVENT_CLICKED, (void*)DRO_AXIS_Z);
    if (objects.set_value_axis4_button) lv_obj_add_event_cb(objects.set_value_axis4_button, event_set_value_request, LV_EVENT_CLICKED, (void*)DRO_AXIS_W);
    if (objects.set_value_axis5_button) lv_obj_add_event_cb(objects.set_value_axis5_button, event_set_value_request, LV_EVENT_CLICKED, (void*)DRO_AXIS_C);

    // Half Button
    if (objects.half_button) lv_obj_add_event_cb(objects.half_button, event_half_request, LV_EVENT_CLICKED, NULL);

    // Tool Button
    if (objects.set_tool_number_button) lv_obj_add_event_cb(objects.set_tool_number_button, event_set_tool_request, LV_EVENT_CLICKED, NULL);

    // Space Button
    if (objects.set_space_number_button) lv_obj_add_event_cb(objects.set_space_number_button, event_set_space_request, LV_EVENT_CLICKED, NULL);

    if (objects.numpad) {
        lv_obj_add_event_cb(objects.numpad, event_numpad_ready, LV_EVENT_READY, NULL);
        lv_obj_add_event_cb(objects.numpad, event_numpad_cancel, LV_EVENT_CANCEL, NULL);
    }
}